const endpoints = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  LOGOUT: "/logout",
  G2TEST: "/g2Test",
  G2STATUS: "/g2Status",
  GSTATUS: "/gStatus",
  GTEST: "/gTest",
  UPDATE_CAR_DETAILS: "/gTest",
  DRIVER_NAVIGATION: "/driverNavigation",
  EXAMINER: "/examiner",
  ADMIN: "/appointment",
  AVAILABLE_TIME_SLOTS: "/getAvailableTimeSlots",
  BOOK_APPOINTMENT: "/bookAppointment",
  SUCCESS_APPOINTMENT: "/successAppointment",
  APPOINTMENT_SLOT: "/appointmentSlot",
  FIND_APPOINTMENT_SLOTS: "/findAppointmentSlot",
  BOOK_APPOINTMENT_SLOT: "/bookAppointmentSlot",
  UPDATE_TEST_RESULTS:"/updateTestResult",
};
export default endpoints;
